#!/bin/bash
#############################################
#                CHBACKLIGHT                #
#############################################
#                                           #
# Recibe un único argumento que puede tener #
# formato "+numero" | "-numero" | "numero"  #
# | "up" | "less"                           #
#                                           #
# Incrementa o decrementa el valor del      #
# brillo de la pantalla en función de dicho #
# argumento.                                #
#                                           #
#############################################
#                                           #
#     Autor: Jorge Gómez Zarzosa            #
#                                           #
#############################################


re='^[0-9]+$'
ACTUAL=`cat /sys/class/backlight/amdgpu_bl0/brightness`
valor=`echo $1 | sed 's/^[+,-]//'`

# Si el valor introducido no es formato aceptado -> ERROR
if [ $# -ne 1 ] || (! [[ $valor =~ $re ]] && [ $1 != "up" ] && [ $1 != "down" ]); then
    echo "error: introduce un numero o up/down" >&2; exit 1
fi

# Comprueba si formato es "+numero"
echo -n $1 | grep + -q

if [ $? -eq 0 ]
then
    sum=`expr $ACTUAL + $valor`
else
    # Comprueba si formato es "-numero"
    echo -n $1 | grep - -q
    if [ $? -eq 0 ]
    then
        sum=`expr $ACTUAL - $valor`
    elif [ $1 == "up" ]    # Si up -> +5
    then
        sum=`expr $ACTUAL + 5`
    elif [ $1 == "down" ]  # Si down -> -5
    then
        sum=`expr $ACTUAL - 5`
    else
        # Cuando formato es "numero"
        sum=$1
    fi
fi

# Limita los valores del brillo de la pantalla
if [ $sum -eq 10 ] || [ $sum -lt 10 ]
then
    sum=10
elif [ $sum -eq 255 ] || [ $sum -gt 255 ]
then
    sum=255
fi

# Debugging
echo "Brillo ajustado a $sum"
# The actual thing
echo $sum > /sys/class/backlight/amdgpu_bl0/brightness
